spring:
  cloud:
    alicloud:
      access-key: LTAI5tN4NKP7mLq69tZJvYuy
      secret-key: CbIS6xlOtX08zIG51yghUZfihqdSbe
      oss:
       endpoint: oss-cn-hangzhou.aliyuncs.com

  application:
    name: mall-third-party

server:
  port: 30000